### ISSUE TITLE
consul 起不来

### ISSUE THREAD

**Issue by molixiaoge** [starsliao/TenSunS#130]
1.按照官方文档执行all_install.sh脚本，生成compose文件，这里需要root权限
2.进入/opt/tensuns 执行 docker compose up 
3.发现consul启动不了日志如下
```
consul        | ==> No private IPv4 address found
consul        | ==> No private IPv4 address found
consul        | ==> No private IPv4 address found
consul        | ==> No private IPv4 address found
```

4./opt/tensuns/docker-compose.yaml如下
```
version: '3.6'
services:
  consul:
    image: swr.cn-south-1.myhuaweicloud.com/starsl.cn/consul:latest
    container_name: consul
    hostname: consul
    restart: always
    ports:
      - "8500:8500"
    volumes:
     - /opt/tensuns/consul/data:/consul/data
     - /opt/tensuns/consul/config:/consul/config
     - /usr/share/zoneinfo/PRC:/etc/localtime
    command: "agent"
    networks:
      - TenSunS

  flask-consul:
    image: swr.cn-south-1.myhuaweicloud.com/starsl.cn/flask-consul:latest
    container_name: flask-consul
    hostname: flask-consul
    restart: always
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
    environment:
      consul_token: 1c7b7526-dd5f-4b3a-98de-6b6435c6e21d
      consul_url: http://consul:8500/v1
      admin_passwd: bba7b9ca
      log_level: INFO
    depends_on:
      - consul
    networks:
      - TenSunS

  nginx-consul:
    image: swr.cn-south-1.myhuaweicloud.com/starsl.cn/nginx-consul:latest
    container_name: nginx-consul
    hostname: nginx-consul
    restart: always
    ports:
      - "1026:1026"
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
    depends_on:
      - flask-consul
    networks:
      - TenSunS

networks:
  TenSunS:
    name: TenSunS
    driver: bridge
    ipam:
      driver: default
```

5./opt/tensuns/consul/config/consul.hcl 如下

```
log_level = "error"
data_dir = "/consul/data"
client_addr = "0.0.0.0"
ui_config{
  enabled = true
}
ports = {
  grpc = -1
  https = -1
  dns = -1
  grpc_tls = -1
  serf_wan = -1
}
peering {
  enabled = false
}
connect {
  enabled = false
}
server = true
bootstrap_expect=1
acl = {
  enabled = true
  default_policy = "deny"
  enable_token_persistence = true
  tokens {
    initial_management = "1c7b7526-dd5f-4b3a-98de-6b6435c6e21d"
    agent = "1c7b7526-dd5f-4b3a-98de-6b6435c6e21d"
  }
}

```
